# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/smn90/Desktop/axi_slave_soc/src/soc_top.xdc

# IP: C:/Users/smn90/Desktop/axi_slave_soc/pll0/pll0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll0 || ORIG_REF_NAME==pll0} -quiet] -quiet

# XDC: c:/Users/smn90/Desktop/axi_slave_soc/pll0/pll0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll0 || ORIG_REF_NAME==pll0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/smn90/Desktop/axi_slave_soc/pll0/pll0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll0 || ORIG_REF_NAME==pll0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/smn90/Desktop/axi_slave_soc/pll0/pll0_ooc.xdc
