#FPGA clock input
create_clock -period 40.000 -name GCLK -waveform {0.000 20.000} [get_ports GCLK]
create_clock -period 27.000 -name rclk -waveform {0.000 12.500} [get_ports {FPGA_PAD[35]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {u_axi_bus_m32_bridge_0/FPGA_PAD_IBUF[35]}]
#FPGA_PADs connection for system
set_property PACKAGE_PIN P17 [get_ports GCLK]
set_property PACKAGE_PIN T8 [get_ports {FPGA_PAD[0]}]
set_property PACKAGE_PIN V9 [get_ports {FPGA_PAD[1]}]
set_property PACKAGE_PIN N6 [get_ports {FPGA_PAD[2]}]
set_property PACKAGE_PIN U6 [get_ports {FPGA_PAD[3]}]
set_property PACKAGE_PIN V6 [get_ports {FPGA_PAD[4]}]
set_property PACKAGE_PIN T6 [get_ports {FPGA_PAD[5]}]
set_property PACKAGE_PIN V4 [get_ports {FPGA_PAD[6]}]
set_property PACKAGE_PIN R6 [get_ports {FPGA_PAD[7]}]
set_property PACKAGE_PIN U4 [get_ports {FPGA_PAD[8]}]
set_property PACKAGE_PIN V2 [get_ports {FPGA_PAD[9]}]
set_property PACKAGE_PIN V1 [get_ports {FPGA_PAD[10]}]
set_property PACKAGE_PIN N5 [get_ports {FPGA_PAD[11]}]
set_property PACKAGE_PIN T5 [get_ports {FPGA_PAD[12]}]
set_property PACKAGE_PIN T3 [get_ports {FPGA_PAD[13]}]
set_property PACKAGE_PIN N4 [get_ports {FPGA_PAD[14]}]
set_property PACKAGE_PIN T1 [get_ports {FPGA_PAD[15]}]
set_property PACKAGE_PIN R2 [get_ports {FPGA_PAD[16]}]
set_property PACKAGE_PIN N1 [get_ports {FPGA_PAD[17]}]
set_property PACKAGE_PIN M1 [get_ports {FPGA_PAD[18]}]
set_property PACKAGE_PIN M3 [get_ports {FPGA_PAD[19]}]
set_property PACKAGE_PIN M2 [get_ports {FPGA_PAD[20]}]
set_property PACKAGE_PIN D8 [get_ports {FPGA_PAD[21]}]
set_property PACKAGE_PIN C7 [get_ports {FPGA_PAD[22]}]
set_property PACKAGE_PIN L1 [get_ports {FPGA_PAD[23]}]
set_property PACKAGE_PIN N2 [get_ports {FPGA_PAD[24]}]
set_property PACKAGE_PIN P2 [get_ports {FPGA_PAD[25]}]
set_property PACKAGE_PIN R1 [get_ports {FPGA_PAD[26]}]
set_property PACKAGE_PIN M4 [get_ports {FPGA_PAD[27]}]
set_property PACKAGE_PIN P3 [get_ports {FPGA_PAD[28]}]
set_property PACKAGE_PIN P4 [get_ports {FPGA_PAD[29]}]
set_property PACKAGE_PIN R3 [get_ports {FPGA_PAD[30]}]
set_property PACKAGE_PIN T4 [get_ports {FPGA_PAD[31]}]
set_property PACKAGE_PIN P5 [get_ports {FPGA_PAD[32]}]
set_property PACKAGE_PIN U1 [get_ports {FPGA_PAD[33]}]
set_property PACKAGE_PIN U2 [get_ports {FPGA_PAD[34]}]
set_property PACKAGE_PIN U3 [get_ports {FPGA_PAD[35]}]
set_property PACKAGE_PIN R5 [get_ports {FPGA_PAD[36]}]
set_property PACKAGE_PIN V5 [get_ports {FPGA_PAD[37]}]
set_property PACKAGE_PIN R7 [get_ports {FPGA_PAD[38]}]
set_property PACKAGE_PIN V7 [get_ports {FPGA_PAD[39]}]
set_property PACKAGE_PIN U7 [get_ports {FPGA_PAD[40]}]
set_property PACKAGE_PIN M6 [get_ports {FPGA_PAD[41]}]
set_property PACKAGE_PIN U9 [get_ports {FPGA_PAD[42]}]
set_property PACKAGE_PIN R8 [get_ports {FPGA_PAD[43]}]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_PAD*]
set_property IOSTANDARD LVCMOS33 [get_ports GCLK]
set_property PULLDOWN true [get_ports {FPGA_PAD[18]}]
set_property SLEW FAST [get_ports FPGA_PAD*]

#Timing exception set
set_false_path -from [get_clocks *clk_out3*] -to [get_clocks *clk_out1*]
set_false_path -from [get_clocks *clk_out1*] -to [get_clocks *clk_out3*]
set_false_path -from [get_clocks *clk_out3*] -to [get_clocks *clk_out2*]
set_false_path -from [get_clocks *clk_out2*] -to [get_clocks *clk_out3*]
set_false_path -from [get_clocks *clk_out1*] -to [get_clocks *clk_out2*]
set_false_path -from [get_clocks *clk_out2*] -to [get_clocks *clk_out1*]
set_false_path -from [get_clocks *clk_out2*] -to [get_clocks *rclk*]
set_false_path -from [get_clocks *rclk*] -to [get_clocks *clk_out2*]
set_false_path -from [get_clocks *clk_out3*] -to [get_clocks *rclk*]
set_false_path -from [get_clocks *rclk*] -to [get_clocks *clk_out3*]
set_false_path -from [get_clocks *rclk*] -to [get_clocks *clk_out1*]
set_false_path -from [get_clocks *clk_out1*] -to [get_clocks *rclk*]
set_false_path -from [get_ports {*FPGA_PAD[18]*}] -to [all_registers]
set_false_path -from [all_registers] -to [get_ports {*FPGA_PAD[19]*}]
set_false_path -from [all_registers] -to [get_ports {*FPGA_PAD[23]*}]

set_max_delay -from [all_registers -edge_triggered] -through [get_nets *FPGA_PAD*] -to [all_outputs] 6.000
set_max_delay -from [all_inputs] -through [get_nets *FPGA_PAD*] -to [all_registers -edge_triggered] 4.000

#FPGA_SPIs connection for user IP
#set_property PACKAGE_PIN B3 [get_ports FPGA_SPI_CLK]
#set_property PACKAGE_PIN C1 [get_ports FPGA_SPI_DI]
#set_property PACKAGE_PIN B2 [get_ports FPGA_SPI_DO]
#set_property PACKAGE_PIN A1 [get_ports FPGA_SPI_CS_B]
#set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SPI*]



set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property CFGBVS GND [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.M1PIN PULLNONE [current_design]
set_property BITSTREAM.CONFIG.M2PIN PULLNONE [current_design]
set_property BITSTREAM.CONFIG.M0PIN PULLNONE [current_design]
set_property BITSTREAM.CONFIG.USR_ACCESS TIMESTAMP [current_design]



set_property MARK_DEBUG true [get_nets axim32_awready]
set_property MARK_DEBUG true [get_nets axim32_awvalid]
set_property MARK_DEBUG true [get_nets axim32_rready]
set_property MARK_DEBUG true [get_nets axim32_rvalid]
set_property MARK_DEBUG true [get_nets axim32_wready]
set_property MARK_DEBUG true [get_nets axim32_wvalid]
set_property MARK_DEBUG true [get_nets {axim32_wdata[3]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[1]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[7]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[11]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[14]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[15]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[26]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[19]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[22]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[29]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[23]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[6]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[0]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[4]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[31]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[10]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[12]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[16]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[18]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[25]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[28]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[2]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[9]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[13]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[20]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[21]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[24]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[5]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[8]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[17]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[27]}]
set_property MARK_DEBUG true [get_nets {axim32_wdata[30]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[8]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[9]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[11]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[17]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[21]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[26]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[30]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[6]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[7]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[15]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[16]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[24]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[25]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[28]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[2]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[0]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[1]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[3]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[4]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[27]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[31]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[5]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[13]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[23]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[20]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[22]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[10]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[12]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[14]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[18]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[19]}]
set_property MARK_DEBUG true [get_nets {axim32_rdata[29]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[8]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[1]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[14]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[15]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[17]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[18]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[19]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[22]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[23]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[9]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[12]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[16]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[20]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[25]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[26]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[10]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[13]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[11]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[21]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[24]}]
set_property MARK_DEBUG true [get_nets {axim32_awaddr[27]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[3]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[5]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[10]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[14]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[24]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[25]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[8]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[13]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[17]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[19]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[26]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[1]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[4]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[6]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[12]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[16]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[20]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[23]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[11]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[0]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[2]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[7]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[9]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[15]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[18]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[21]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[22]}]
set_property MARK_DEBUG true [get_nets {axim32_araddr[27]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_axi_bus_m32_bridge_0/sysclk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {axim32_rdata[0]} {axim32_rdata[1]} {axim32_rdata[2]} {axim32_rdata[3]} {axim32_rdata[4]} {axim32_rdata[5]} {axim32_rdata[6]} {axim32_rdata[7]} {axim32_rdata[8]} {axim32_rdata[9]} {axim32_rdata[10]} {axim32_rdata[11]} {axim32_rdata[12]} {axim32_rdata[13]} {axim32_rdata[14]} {axim32_rdata[15]} {axim32_rdata[16]} {axim32_rdata[17]} {axim32_rdata[18]} {axim32_rdata[19]} {axim32_rdata[20]} {axim32_rdata[21]} {axim32_rdata[22]} {axim32_rdata[23]} {axim32_rdata[24]} {axim32_rdata[25]} {axim32_rdata[26]} {axim32_rdata[27]} {axim32_rdata[28]} {axim32_rdata[29]} {axim32_rdata[30]} {axim32_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 28 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {axim32_awaddr[0]} {axim32_awaddr[1]} {axim32_awaddr[2]} {axim32_awaddr[3]} {axim32_awaddr[4]} {axim32_awaddr[5]} {axim32_awaddr[6]} {axim32_awaddr[7]} {axim32_awaddr[8]} {axim32_awaddr[9]} {axim32_awaddr[10]} {axim32_awaddr[11]} {axim32_awaddr[12]} {axim32_awaddr[13]} {axim32_awaddr[14]} {axim32_awaddr[15]} {axim32_awaddr[16]} {axim32_awaddr[17]} {axim32_awaddr[18]} {axim32_awaddr[19]} {axim32_awaddr[20]} {axim32_awaddr[21]} {axim32_awaddr[22]} {axim32_awaddr[23]} {axim32_awaddr[24]} {axim32_awaddr[25]} {axim32_awaddr[26]} {axim32_awaddr[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {axim32_wdata[0]} {axim32_wdata[1]} {axim32_wdata[2]} {axim32_wdata[3]} {axim32_wdata[4]} {axim32_wdata[5]} {axim32_wdata[6]} {axim32_wdata[7]} {axim32_wdata[8]} {axim32_wdata[9]} {axim32_wdata[10]} {axim32_wdata[11]} {axim32_wdata[12]} {axim32_wdata[13]} {axim32_wdata[14]} {axim32_wdata[15]} {axim32_wdata[16]} {axim32_wdata[17]} {axim32_wdata[18]} {axim32_wdata[19]} {axim32_wdata[20]} {axim32_wdata[21]} {axim32_wdata[22]} {axim32_wdata[23]} {axim32_wdata[24]} {axim32_wdata[25]} {axim32_wdata[26]} {axim32_wdata[27]} {axim32_wdata[28]} {axim32_wdata[29]} {axim32_wdata[30]} {axim32_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 28 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {axim32_araddr[0]} {axim32_araddr[1]} {axim32_araddr[2]} {axim32_araddr[3]} {axim32_araddr[4]} {axim32_araddr[5]} {axim32_araddr[6]} {axim32_araddr[7]} {axim32_araddr[8]} {axim32_araddr[9]} {axim32_araddr[10]} {axim32_araddr[11]} {axim32_araddr[12]} {axim32_araddr[13]} {axim32_araddr[14]} {axim32_araddr[15]} {axim32_araddr[16]} {axim32_araddr[17]} {axim32_araddr[18]} {axim32_araddr[19]} {axim32_araddr[20]} {axim32_araddr[21]} {axim32_araddr[22]} {axim32_araddr[23]} {axim32_araddr[24]} {axim32_araddr[25]} {axim32_araddr[26]} {axim32_araddr[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list axim32_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list axim32_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list axim32_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list axim32_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list axim32_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list axim32_wvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_sysclk_IBUF_BUFG]
